apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
replicas:
  - name: ${APP_NAME}
    count: 1
patches:
  - target:
      kind: ConfigMap
      name: ${APP_NAME}-config
    patch: |-
      - op: add
        path: /data/SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "update"
      - op: add
        path: /data/APP_DATA_SEED_ENABLED
        value: "true"
      - op: add
        path: /data/DB_NAME
        value: "${DB_NAME}"
      - op: add
        path: /data/AWS_S3_BUCKET
        value: "${S3_BUCKET_NAME}"
  - target:
      kind: Ingress
      name: ${APP_NAME}-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ${INGRESS_HOST}
