apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntt-data-dev
resources:
  - ../../base
replicas:
  - name: nttdata
    count: 1
images:
  - name: nttdata
    newName: /nttdata
    newTag: dev
patches:
  - target:
      kind: ConfigMap
      name: nttdata-config
    patch: |-
      - op: add
        path: /data/SPRING_JPA_HIBERNATE_DDL_AUTO
        value: "update"
      - op: add
        path: /data/APP_DATA_SEED_ENABLED
        value: "true"
      - op: add
        path: /data/DB_NAME
        value: "nttdata_dev"
      - op: add
        path: /data/AWS_S3_BUCKET
        value: "nttdata-dev"
  - target:
      kind: Ingress
      name: nttdata-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-api.tu-dominio.com
