name: CI
on:
  push:
    branches: [main]

env:
  NOMBRE_DEL_REPO: mi_primer_repo_con_actions
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - run: echo ${{env.NOMBRE_DEL_REPO}}
      - run: |
           REPO=${{env.NOMBRE_DEL_REPO}}-DEV
           echo $REPO




    
