name: CI-DEV-JAVA
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7

      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin

      - name: Compilar Java
        run: mvn -B clean compile

      - name: compartir compilacion
        uses: actions/upload-artifact@v7
        with:
          name: compilacion-and-generate-artifact
          path: target/

  test:
    name: Pruebas unitarias
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
        
      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: compilacion-and-generate-artifact
          path: target/
      - name: Ejecutar pruebas unitarias
        run: mvn -B test

      - name: compartir test generados
        uses: actions/upload-artifact@v7
        with:
          name: test-generados
          path: target/
    
  
  package:
    name: Empaquetar codigo
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: test-generados
          path: target/
      - name: Ejecutar pruebas unitarias
        run: mvn -B package -DskipTests

      - name: compartir package generado
        uses: actions/upload-artifact@v7
        with:
          name: package-generado
          path: target/
          retention-days: 1
  
  public-nexus:
    name: Publicar en Nexus
    needs: package
    runs-on: self-hosted
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
      - name: download actions java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: temurin
      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: package-generado
          path: target/
      - name: Configurar Nexus
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>nexus-releases</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
              <server>
                <id>nexus-snapshots</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Publicar en Nexus
        env:
          NEXUS_RELEASES_URL: ${{ vars.NEXUS_RELEASES_URL }}
          NEXUS_SNAPSHOTS_URL: ${{ vars.NEXUS_SNAPSHOTS_URL }}
        run: mvn deploy -DskipTests
    
  docker-hub-push:
    name: Docker Build an Push
    needs: public-nexus
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo workspace actions
        uses: actions/checkout@v7
      - name: Restaurar binario compilado en build
        uses: actions/download-artifact@v7
        with:
          name: package-generado
          path: target/
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/ntt-class:$IMAGE_TAG .
      - name: Push Docker Image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE=${{ vars.DOCKERHUB_USERNAME }}/ntt-class:$IMAGE_TAG
          docker push $IMAGE:IMAGE_TAG
          docker tag $IMAGE:dev

          echo "image=$IMAGE:IMAGE_TAG" >> "$GITHUB_OUTPUT"
  deploy:
    name: Deploy to minikube
    needs: docker-hub-push
    runs-on: self-hosted
    steps:
      - name: Clone repositori
        uses: actions/checkout@v7
      
      - name: Crear secret en k8s minikube
        run: |
          kubectl create secret generic nttdata-secret \
            --from-literal=SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            --from-literal=SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            --from-literal=JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }} \
            --from-literal=AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
      - name: custom kustomize
        uses: imranismail/setup-kustomize@v3
      
      - name: Pull Tag and deploy
        working-directory: k8s/manifest/overlays/dev
        run: kustomize edit set image nttdata=${{ needs.docker-hub-push.outputs.image }}
      
      - name: aplicar manifestos k8s
        working-directory: k8s/manifest/overlays/dev
        run: kubectl apply -k .
       
         
          