name: CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
  workflow_dispatch:
    inputs:
      deploy-target:
        description: "Forzar destino"
        type: choice
        options: [onpremise, cloud]

jobs:
  setup:
    name: Resolver destino
    runs-on: ubuntu-latest
    outputs:
      deploy_target: ${{ steps.resolve.outputs.target }}
    steps:
      - name: Resolver DEPLOY_TARGET
        id: resolve
        run: |
          TARGET="${{ github.event.inputs.deploy-target }}"
          if [ -z "$TARGET" ]; then
            TARGET="${{ vars.DEPLOY_TARGET }}"
          fi
          echo "Usando destino: $TARGET"
          echo "target=$TARGET" >> "$GITHUB_OUTPUT"

  build:
    needs: setup
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml

  package:
    needs: test
    uses: ./.github/workflows/package.yml
    with:
      skip-tests: false 

  sonar-analysis:
    needs: package
    if: ${{ vars.ENABLE_SONAR == 'true' }}
    uses: ./.github/workflows/sonar-analize.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  nexus-publish:
    needs: [package, sonar-analysis]
    if: ${{ always() && !failure() && !cancelled() && github.event_name == 'push' }}
    uses: ./.github/workflows/nexus-publish.yml
    with:
      runner: ${{ vars.NEXUS_RUNNER || 'ubuntu-latest' }}
    secrets:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  docker-push:
    needs: [setup, nexus-publish]
    if: ${{ always() && !failure() && !cancelled() && github.event_name == 'push' }}
    uses: ./.github/workflows/docker-push.yml
    permissions:
      contents: read
      id-token: write 
      security-events: write
    with:
      target: ${{ needs.setup.outputs.deploy_target }}
      dockerhub-repository: ${{ vars.DOCKERHUB_REPOSITORY }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      aws-region: ${{ vars.AWS_REGION }}
      mutable-tag: dev
      scan-image: ${{ needs.setup.outputs.deploy_target == 'cloud' }}
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}


  deploy:
    needs: [setup, docker-push]
    if: ${{ always() && !failure() && !cancelled() && github.event_name == 'push' }}
    uses: ./.github/workflows/k8s-deploy.yml
    permissions:
      contents: read
      id-token: write 
      security-events: write
    with:
      cluster-type: ${{ needs.setup.outputs.deploy_target == 'cloud' && 'eks' || 'minikube' }}
      runner: ${{ needs.setup.outputs.deploy_target == 'cloud' && 'ubuntu-latest' || 'self-hosted' }}
      namespace: ${{ needs.setup.outputs.deploy_target == 'cloud' && vars.NAMESPACE_CLOUD || vars.NAMESPACE_ONPREM }}
      deployment-name: ${{ vars.APP_NAME }}
      image: ${{ needs.docker-push.outputs.image }}
      manifests-path: ${{ needs.setup.outputs.deploy_target == 'cloud' && vars.MANIFESTS_PATH_CLOUD || vars.MANIFESTS_PATH_ONPREM }}
      manifests-external-repo: ${{ needs.setup.outputs.deploy_target == 'cloud' && vars.MANIFESTS_EXTERNAL_REPO || '' }}
      aws-region: ${{ vars.AWS_REGION }}
      eks-cluster-name: ${{ vars.EKS_CLUSTER_NAME }}
      db-name: ${{ vars.DB_NAME }}
      s3-bucket-name: ${{ vars.S3_BUCKET_NAME }}
      ingress-host: ${{ vars.INGRESS_HOST }}
    secrets:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
      AWS_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}
      MANIFESTS_REPO_TOKEN: ${{ secrets.MANIFESTS_REPO_TOKEN }}
